### ISSUE TITLE
Set recent caps on convert

### ISSUE THREAD

**Issue by tonistiigi** [po3rin/dockerdot#1]
The recent versions of buildkit (and Docker 19.03) do not use `dockerfile-copy` helper anymore for `ADD/COPY` instructions. The image is only used when building for older daemons. You can set the `LLBCaps` on convert to generate a graph as it would be run on updated buildkit.

**Comment by po3rin** [comment]
Thank you for Issue.

I set the LLBCaps in ```dockerfile2llb.ConvertOpt```
#2
